# 当前工作流的名称
name: sub-web-deploy
on:
  push:
    branches:
      - master

jobs: # 构建的任务，一个工作流可以有多个构建任务
  build-and-deploy:
    runs-on: ubuntu-latest # 在什么服务器上执行这些任务，这里使用最新版本的Ubuntu系统
    
    steps: # 构建任务的步骤，一个任务可分为多个步骤
      # 步骤1 切换分支
      - name: Checkout
        uses: actions/checkout@v4
      # 步骤2 安装Node.js
      - name: use node
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18
      # 步骤3 下载项目依赖    
      - name: install
        run: npm install
      # 步骤4 打包Node.js项目
      - name: build
        run: npm run docs:build
      # 步骤5 部署项目到服务器
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v4.1.10
        with:
          # SSH密钥的私钥部分
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # 远程主机地址
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          # 远程主机用户名
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          # 源目录，相对于 `$GITHUB_WORKSPACE` 的根路径，例如：`dist/`
          SOURCE: "/dist/"
          # 目标目录
          TARGET: "/www/wwwroot/www.fanliu.top/"
